CREATE TABLE [dbo].[DataAccessRules](
	[RuleId] [int] NOT NULL,
	[RuleName] [varchar](150) NULL,
	[RuleDescription] [varchar](max) NULL,
 CONSTRAINT [PK_DataAccessRules] PRIMARY KEY CLUSTERED 
(
	[RuleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]