CREATE TABLE [dbo].[ResponseXml](
	[ResponseId] [uniqueidentifier] NOT NULL,
	[Xml] [xml] NOT NULL,
	[UserId] [int] NULL,
	[IsNewRecord] [bit] NULL,
 CONSTRAINT [PK_ResponseXml] PRIMARY KEY CLUSTERED 
(
	[ResponseId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]