CREATE TABLE [dbo].[SharedCanvases](
	[CanvasID] [INT] NOT NULL,
	[UserID] [INT] NOT NULL,
 CONSTRAINT [PK_CanvasUser] PRIMARY KEY CLUSTERED 
(
	[CanvasID] ASC,
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SharedCanvases]  WITH CHECK ADD  CONSTRAINT [FK_CanvasUser_User] FOREIGN KEY([UserID])
REFERENCES [dbo].[User] ([UserID])
GO

ALTER TABLE [dbo].[SharedCanvases] CHECK CONSTRAINT [FK_CanvasUser_User]